// <auto-generated />
namespace XnNationalDefenseMobilize.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddTimeForCommQus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTimeForCommQus));
        
        string IMigrationMetadata.Id
        {
            get { return "201609031446455_AddTimeForCommQus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
